//
// Unit tests for include/driver/base.h — BaseDriver class.
//
// Verifies:
//   - parse_config<T>() parses valid JSON correctly.
//   - parse_config<T>() throws ParamParseException on missing keys.
//   - parse_config<T>() throws ParamParseException on malformed JSON.
//   - get_abi_version() returns a non-zero, sane constant.
//   - BaseDriver can be inherited and used as the default Driver interface.
// =============================================================================

#include <string>
#include <optional>
#include <type_traits>

#include <gtest/gtest.h>
#include <glaze/glaze.hpp>

#include "driver/base.h"
#include "driver/exceptions.h"
#include "interface/abi_version.h"

// ── Test fixture: a minimal concrete subclass of BaseDriver ──────────────────

class TestDriver final : public BaseDriver {
public:
    // Expose protected parse_config publicly for testing.
    using BaseDriver::parse_config;

    [[nodiscard]] DriverRequestContext generate_request(
        const DriverConfig &config, const DriverUpdateParams &ctx
    ) const override {
        // Minimal implementation: return a dummy request.
        return {.url = "https://example.com/update", .request = {}};
    }

    [[nodiscard]] bool check_response(const HttpResponse &response) const override {
        // Accept any 2xx response.
        return response.status_code >= 200 && response.status_code < 300;
    }

    [[nodiscard]] DriverDetail get_detail() const noexcept override {
        return {.name = "test", .description = "Test driver", .author = "test", .version = "1.0.0"};
    }
};

// ── Test config struct for parse_config testing ─────────────────────────────
struct TestConfig {
    std::string api_key;
    std::string endpoint;
    std::optional<int> ttl{300};
    std::optional<bool> enabled{true};
};

template <>
struct glz::meta<TestConfig> {
    using T = TestConfig;
    static constexpr auto value = glz::object(
        "api_key", &T::api_key,
        "endpoint", &T::endpoint,
        "ttl", &T::ttl,
        "enabled", &T::enabled
    );
};

// ── Tests ──────────────────────────────────────────────────────────────────

TEST(BaseDriverTest, GetAbiVersion_ReturnsNonZeroVersion) {
    TestDriver driver;
    auto ver = driver.get_abi_version();
    // ABI version should have reasonable values.
    EXPECT_GE(ver.major, 0u);
    EXPECT_GE(ver.minor, 0u);
    EXPECT_GE(ver.patch, 0u);
    // The version constant is at least 1.0.0 — we can't know the exact value
    // (it's generated by CMake), but we can verify it's a valid struct.
    static_assert(std::is_same_v<decltype(DRV_ABI_VERSION), const AbiVersion>);
}

TEST(BaseDriverTest, GetAbiVersion_IsCompatibleWithItself) {
    TestDriver driver;
    auto ver = driver.get_abi_version();
    EXPECT_TRUE(ver.is_compatible_with(ver));
}

TEST(BaseDriverTest, GetAbiVersion_AbiVersionType) {
    // DRV_ABI_VERSION is constexpr const AbiVersion
    static_assert(std::is_same_v<const AbiVersion, decltype(DRV_ABI_VERSION)>);
}

TEST(BaseDriverTest, ParseConfig_ValidJson_Succeeds) {
    auto json = R"({"api_key":"abc123","endpoint":"https://api.example.com","ttl":600})";
    auto cfg = TestDriver::parse_config<TestConfig>(json);
    EXPECT_EQ(cfg.api_key, "abc123");
    EXPECT_EQ(cfg.endpoint, "https://api.example.com");
    EXPECT_EQ(cfg.ttl, 600);
    EXPECT_EQ(cfg.enabled, true);
}

TEST(BaseDriverTest, ParseConfig_ValidJson_OptionalOmitted_UsesDefault) {
    // "enabled" is optional<bool> with default true; "ttl" is also optional with default 300.
    auto json = R"({"api_key":"key","endpoint":"https://example.com"})";
    auto cfg = TestDriver::parse_config<TestConfig>(json);
    EXPECT_EQ(cfg.api_key, "key");
    EXPECT_EQ(cfg.ttl, 300);          // optional default
    EXPECT_EQ(cfg.enabled, true);     // optional default
}

TEST(BaseDriverTest, ParseConfig_MissingRequiredKey_ThrowsParamParseException) {
    auto json = R"({"api_key":"abc123"})";  // missing "endpoint" (required)
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_EmptyObject_ThrowsParamParseException) {
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>("{}"); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_MalformedJson_ThrowsParamParseException) {
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>("{invalid}"); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_EmptyString_ThrowsParamParseException) {
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(""); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_TypeMismatch_ThrowsParamParseException) {
    // ttl is int but we provide a string.
    auto json = R"({"api_key":"key","endpoint":"https://example.com","ttl":"not_a_number"})";
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_ExtraKeysCausesError) {
    // glaze with error_on_missing_keys=true also rejects unknown/extra keys.
    auto json = R"({"api_key":"k","endpoint":"https://e.com","extra_field":"ignored"})";
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json); },
        ParamParseException
    );
}

// ── Inheritance check ──────────────────────────────────────────────────────

TEST(BaseDriverTest, TestDriver_IsBaseDriver) {
    static_assert(std::is_base_of_v<BaseDriver, TestDriver>);
}

TEST(BaseDriverTest, BaseDriver_IsDriver) {
    static_assert(std::is_base_of_v<Driver, BaseDriver>);
}

// ── Default execute flow ───────────────────────────────────────────────────
// Note: BaseDriver's execute() delegates to generate_request, then
// http.exchange(), then check_response().  A full test would require a
// MockHttpClient.  Here we only verify the method signature compiles and
// that the default return value is reachable via a subclass.

TEST(BaseDriverTest, Execute_RequiresHttpClient) {
    TestDriver driver;
    DriverConfig cfg = R"({"api_key":"test","endpoint":"https://e.com"})";
    DriverUpdateParams params{
        .ip_addr = "1.2.3.4",
        .rd_type = "A",
        .domain = "example.com",
        .subdomain = "@",
        .fqdn = "example.com"
    };
    // We cannot call execute() without an HttpClient instance in this test,
    // but we can verify the signature compiles and that the method exists.
    SUCCEED();
}
