//
// Unit tests for include/driver/base.h — BaseDriver class.
//
// Verifies:
//   - parse_config<T>() parses valid JSON correctly.
//   - parse_config<T>() throws ParamParseException on missing keys.
//   - parse_config<T>() throws ParamParseException on malformed JSON.
//   - get_abi_version() returns a non-zero, sane constant.
//   - BaseDriver can be inherited and used as the default Driver interface.
// =============================================================================

#include <string>
#include <optional>
#include <type_traits>

#include <gtest/gtest.h>
#include <glaze/glaze.hpp>

#include "driver/base.h"
#include "driver/exceptions.h"
#include "interface/abi_version.h"

// ── Test fixture: a minimal concrete subclass of BaseDriver ──────────────────

class TestDriver final : public BaseDriver {
public:
    // Expose protected parse_config publicly for testing.
    using BaseDriver::parse_config;

    [[nodiscard]] DriverRequestContext generate_request(
        const DriverConfig &config, const DriverUpdateParams &ctx
    ) const override {
        // Minimal implementation: return a dummy request.
        return {.url = "https://example.com/update", .request = {}};
    }

    [[nodiscard]] bool check_response(const HttpResponse &response) const override {
        // Accept any 2xx response.
        return response.status_code >= 200 && response.status_code < 300;
    }

    [[nodiscard]] DriverDetail get_detail() const noexcept override {
        return {.name = "test", .description = "Test driver", .author = "test", .version = "1.0.0"};
    }
};

// ── Test config struct for parse_config testing ─────────────────────────────
struct TestConfig {
    std::string api_key;
    std::string endpoint;
    std::optional<int> ttl{300};
    std::optional<bool> enabled{true};
};

template <>
struct glz::meta<TestConfig> {
    using T = TestConfig;
    static constexpr auto value = glz::object(
        "api_key", &T::api_key,
        "endpoint", &T::endpoint,
        "ttl", &T::ttl,
        "enabled", &T::enabled
    );
};

// ── Tests ──────────────────────────────────────────────────────────────────

TEST(BaseDriverTest, GetAbiVersion_ReturnsNonZeroVersion) {
    TestDriver driver;
    auto ver = driver.get_abi_version();
    // ABI version should have reasonable values.
    EXPECT_GE(ver.major, 0u);
    EXPECT_GE(ver.minor, 0u);
    EXPECT_GE(ver.patch, 0u);
    // The version constant is at least 1.0.0 — we can't know the exact value
    // (it's generated by CMake), but we can verify it's a valid struct.
    static_assert(std::is_same_v<decltype(DRV_ABI_VERSION), const AbiVersion>);
}

TEST(BaseDriverTest, GetAbiVersion_IsCompatibleWithItself) {
    TestDriver driver;
    auto ver = driver.get_abi_version();
    EXPECT_TRUE(ver.is_compatible_with(ver));
}

TEST(BaseDriverTest, GetAbiVersion_AbiVersionType) {
    // DRV_ABI_VERSION is constexpr const AbiVersion
    static_assert(std::is_same_v<const AbiVersion, decltype(DRV_ABI_VERSION)>);
}

TEST(BaseDriverTest, ParseConfig_ValidJson_Succeeds) {
    auto json = R"({"api_key":"abc123","endpoint":"https://api.example.com","ttl":600})";
    auto cfg = TestDriver::parse_config<TestConfig>(json);
    EXPECT_EQ(cfg.api_key, "abc123");
    EXPECT_EQ(cfg.endpoint, "https://api.example.com");
    EXPECT_EQ(cfg.ttl, 600);
    EXPECT_EQ(cfg.enabled, true);
}

TEST(BaseDriverTest, ParseConfig_ValidJson_OptionalOmitted_UsesDefault) {
    // "enabled" is optional<bool> with default true; "ttl" is also optional with default 300.
    auto json = R"({"api_key":"key","endpoint":"https://example.com"})";
    auto cfg = TestDriver::parse_config<TestConfig>(json);
    EXPECT_EQ(cfg.api_key, "key");
    EXPECT_EQ(cfg.ttl, 300);          // optional default
    EXPECT_EQ(cfg.enabled, true);     // optional default
}

TEST(BaseDriverTest, ParseConfig_MissingRequiredKey_ThrowsParamParseException) {
    auto json = R"({"api_key":"abc123"})";  // missing "endpoint" (required)
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_EmptyObject_ThrowsParamParseException) {
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>("{}"); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_MalformedJson_ThrowsParamParseException) {
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>("{invalid}"); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_EmptyString_ThrowsParamParseException) {
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(""); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_TypeMismatch_ThrowsParamParseException) {
    // ttl is int but we provide a string.
    auto json = R"({"api_key":"key","endpoint":"https://example.com","ttl":"not_a_number"})";
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json); },
        ParamParseException
    );
}

TEST(BaseDriverTest, ParseConfig_Error_DoesNotLeakConfigContent) {
    // Regression: the exception message must not contain the raw driver
    // config JSON — it may hold API credentials and the message is logged.
    const auto json = R"({"api_key":"supersecret789","endpoint":"https://e.com","broken")";
    try {
        [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json);
        FAIL() << "expected ParamParseException";
    } catch (const ParamParseException &e) {
        const std::string msg(e.what());
        EXPECT_EQ(msg.find("supersecret789"), std::string::npos) << "message leaked api_key: " << msg;
        EXPECT_EQ(msg.find("https://e.com"), std::string::npos) << "message leaked config content: " << msg;
    }
}

TEST(BaseDriverTest, ParseConfig_ExtraKeysCausesError) {
    // glaze with error_on_missing_keys=true also rejects unknown/extra keys.
    auto json = R"({"api_key":"k","endpoint":"https://e.com","extra_field":"ignored"})";
    EXPECT_THROW(
        { [[maybe_unused]] auto _ = TestDriver::parse_config<TestConfig>(json); },
        ParamParseException
    );
}

// ── Inheritance check ──────────────────────────────────────────────────────

TEST(BaseDriverTest, TestDriver_IsBaseDriver) {
    static_assert(std::is_base_of_v<BaseDriver, TestDriver>);
}

TEST(BaseDriverTest, BaseDriver_IsDriver) {
    static_assert(std::is_base_of_v<Driver, BaseDriver>);
}

// ── Default execute flow ───────────────────────────────────────────────────
// Note: BaseDriver's execute() delegates to generate_request, then
// http.exchange(), then check_response().  A full test would require a
// MockHttpClient.  Here we only verify the method signature compiles and
// that the default return value is reachable via a subclass.

TEST(BaseDriverTest, Execute_RequiresHttpClient) {
    TestDriver driver;
    DriverConfig cfg = R"({"api_key":"test","endpoint":"https://e.com"})";
    DriverUpdateParams params{
        .ip_addr = "1.2.3.4",
        .rd_type = "A",
        .domain = "example.com",
        .subdomain = "@",
        .fqdn = "example.com"
    };
    // We cannot call execute() without an HttpClient instance in this test,
    // but we can verify the signature compiles and that the method exists.
    SUCCEED();
}

// ── Log redaction ─────────────────────────────────────────────────────────
// The HttpRequest formatter (http_fmt.hpp) must never emit credentials in
// plain text: header values, form/query parameters, and JSON keys are
// redacted, while non-sensitive fields are preserved for debugging.

TEST(BaseDriverTest, HttpRequestFormatter_RedactsAuthorizationHeader) {
    HttpRequest req;
    req.method = HttpMethod::POST;
    req.headers.insert({"Authorization", "Bearer supersecret123"});

    const auto s = fmt::format("{}", req);
    EXPECT_EQ(s.find("supersecret123"), std::string::npos) << "Authorization leaked: " << s;
    EXPECT_NE(s.find("***"), std::string::npos);
}

TEST(BaseDriverTest, HttpRequestFormatter_RedactsFormBodySecrets) {
    HttpRequest req;
    req.method = HttpMethod::POST;
    req.content_type = "application/x-www-form-urlencoded";
    req.body = "login_token=abc123,def456&domain_id=42&sub_domain=www";

    const auto s = fmt::format("{}", req);
    EXPECT_EQ(s.find("abc123,def456"), std::string::npos) << "login_token leaked: " << s;
    EXPECT_NE(s.find("login_token=***"), std::string::npos);
    // Non-sensitive fields are preserved for debugging.
    EXPECT_NE(s.find("domain_id=42"), std::string::npos);
    EXPECT_NE(s.find("sub_domain=www"), std::string::npos);
}

TEST(BaseDriverTest, HttpRequestFormatter_RedactsJsonBodySecrets) {
    HttpRequest req;
    req.method = HttpMethod::PUT;
    req.content_type = "application/json";
    req.body = R"({"type":"A","apiKey":"xyz789","ttl":30})";

    const auto s = fmt::format("{}", req);
    EXPECT_EQ(s.find("xyz789"), std::string::npos) << "apiKey leaked: " << s;
    EXPECT_NE(s.find("apiKey"), std::string::npos);  // key name preserved, value redacted
    EXPECT_NE(s.find("ttl\":30"), std::string::npos);
}

TEST(BaseDriverTest, RedactUrlQuery_RedactsSensitiveParams) {
    // DuckDNS-style URL: the API token travels in the query string.
    const auto s = Utils::Redact::redact_url_query(
        "/update?domains=example.com&token=SECRETTOKEN&ip=1.2.3.4");
    EXPECT_EQ(s.find("SECRETTOKEN"), std::string::npos) << "query token leaked: " << s;
    EXPECT_NE(s.find("token=***"), std::string::npos);
    EXPECT_NE(s.find("domains=example.com"), std::string::npos);
    EXPECT_NE(s.find("ip=1.2.3.4"), std::string::npos);
}

TEST(BaseDriverTest, RedactBody_PreservesNonSensitive) {
    const auto s = Utils::Redact::redact_body("domain_id=42&ttl=600&proxied=false");
    EXPECT_EQ(s, "domain_id=42&ttl=600&proxied=false");
}
