name: GitHub auto build

on:
  push:
    branches: [master, dev, v0.x]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/**"
  pull_request:
    branches: [master, dev, v0.x]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y libssl-dev zlib1g zlib1g-dev pkg-config
      - name: Build
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug && make -s -C build -j$(nproc)
  linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y libssl-dev zlib1g zlib1g-dev pkg-config
      - name: Build
        env:
          CC: gcc-14
          CXX: g++-14
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug && make -s -C build -j$(nproc)
  linux-amd64-musl:
    runs-on: ubuntu-24.04
    container: alpine:3
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        run: apk add --no-cache build-base git cmake openssl-dev zlib-dev pkgconfig
      - name: Build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug && make -s -C build -j$(nproc)
  macos-arm64:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install dependencies
        run: brew update; brew install openssl@3 pkg-config
      - name: Build
        run: cmake -B build -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3/ -DCMAKE_BUILD_TYPE=Debug && make -s -C build -j$(nproc)
