name: GitHub auto build

on: [ push, pull_request ]

jobs:
  linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive --depth 1
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y libssl-dev zlib1g zlib1g-dev
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Run cmake for debug build
        run: cd build-debug && cmake ../ -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cd build-debug && make -s -j 2
      - name: Run cmake for release build
        run: cd build-release && cmake ../ -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cd build-release && make -s -j 2

  linux-aarch64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive --depth 1
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Build on aarch64 enviroment
        uses: uraimo/run-on-arch-action@v1.0.9
        id: runcmd
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
            apt update && DEBIAN_FRONTEND=noninteractive apt -y install build-essential libssl-dev zlib1g zlib1g-dev cmake git
            cd build-debug && cmake ../ -DCMAKE_BUILD_TYPE=Debug
            make -s -j 2
            cd ../build-release && cmake ../ -DCMAKE_BUILD_TYPE=Release
            make -s -j 2

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive --depth 1
      - name: Install dependencies
        run: brew update; brew install openssl@1.1
      - name: Create build directory
        run: mkdir build{-debug,-release}
      - name: Run cmake for debug build
        run: cd build-debug && cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/ -DCMAKE_BUILD_TYPE=Debug
      - name: Build debug
        run: cd build-debug && make -s -j 2
      - name: Run cmake for release build
        run: cd build-release && cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/ -DCMAKE_BUILD_TYPE=Release
      - name: Build release
        run: cd build-release && make -s -j 2
