name: GitHub auto build

on: [ push, pull_request ]

jobs:
  linux-amd64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive --depth 1
      - name: Install dependencies
        run: sudo apt update; sudo apt install -y libssl-dev zlib1g zlib1g-dev
      - name: Create build directory
        run: mkdir build
      - name: Build
        run: cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug && make -s -j 2

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Checkout submodule
        run: |
          git submodule update --init --recursive --depth 1
      - name: Install dependencies
        run: brew update; brew install openssl@1.1
      - name: Create build directory
        run: mkdir build
      - name: Build
        run: cd build && cmake ../ -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1/ -DCMAKE_BUILD_TYPE=Debug && make -s -j 2
