name: CI — unit tests

on:
    push:
        branches: [master, dev, v0.x]
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "LICENSE"
            - ".github/**"
    pull_request:
        branches: [master, dev, v0.x]
        paths-ignore:
            - "**.md"
            - ".gitignore"
            - "LICENSE"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    linux-amd64:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Install dependencies
              run: sudo apt update; sudo apt install -y ninja-build libssl-dev zlib1g zlib1g-dev pkg-config
            - name: Configure
              env:
                  CC: gcc-14
                  CXX: g++-14
              run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DYADDNSC_BUILD_TESTS=ON
            - name: Build
              env:
                  CC: gcc-14
                  CXX: g++-14
              run: ninja -C build -j$(nproc)
            - name: Test
              env:
                  CC: gcc-14
                  CXX: g++-14
              run: ctest --test-dir build --output-on-failure -j$(nproc)

    linux-amd64-musl:
        runs-on: ubuntu-24.04
        container: alpine:3
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Install dependencies
              run: apk add --no-cache build-base git cmake samurai openssl-dev zlib-dev pkgconfig
            - name: Configure
              run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DYADDNSC_BUILD_TESTS=ON
            - name: Build
              run: ninja -C build -j$(nproc)
            - name: Test
              run: ctest --test-dir build --output-on-failure -j$(nproc)

    macos-arm64:
        runs-on: macos-26
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Install dependencies
              run: brew update; brew install ninja openssl@3 pkg-config
            - name: Configure
              run: cmake -B build -G Ninja -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3/ -DCMAKE_BUILD_TYPE=Debug -DYADDNSC_BUILD_TESTS=ON
            - name: Build
              run: ninja -C build -j$(getconf _NPROCESSORS_ONLN)
            - name: Test
              run: ctest --test-dir build --output-on-failure -j$(getconf _NPROCESSORS_ONLN)
